Prueba-master/Projects/Consumir Aplicacion/Consumir Aplicacion/Controllers/SftpController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Consumir_Aplicacion.Models;
using Consumir_Aplicacion.WsBlackBoard;
using System.Text;
using System.Web.Helpers;
using System.Xml;
using System.Data;
using System.Net;
namespace Consumir_Aplicacion.Controllers
{
    public class SftpController : Controller
    {
        SftpModels objeto = new SftpModels();

        SwnBlackBoardClient cliente = new SwnBlackBoardClient();
        #region Declaracion de variables
        private static string url = "https://universidadinsurgentes-sandbox.mrooms.net/blocks/conduit/webservices/rest";
        private static string token = "token=55fa8fa9-cf0c-40d2-886f-b3a5c4123aa0";
        private static string pobjAdjuntarSlash = "/";
        private static string pobjAdjuntar = "&";
        private static string pobjMetodoex = "method=";
        private static string pobjExtension = ".php?";
        private List<string> Urls;
        private string pobjstrFiltro;
        string metodo = string.Empty;
        private DataTable pobjDtResultadoCalificacion;
        private DataTable pobjDtResultado;
        public enum endPoints
        {
            course = 1,
            enroll = 2,
            groups = 3,
            role_assign = 4,
            user = 5
        }
        public enum Metodos
        {
            get_course,
            get_course_grades,
            get_groups,
            get_user,
            get_user_course_recent_activity,
            get_user_course_activities_due,
            get_user_course_events,
            get_user_grades

        }

        #endregion





        // GET: /Sftp/

        public ActionResult Index()
        {


            return View();
        }


        [HttpPost]
        public ActionResult Index(SftpModels sftp)
        {
            string nombreArchivo;
            try
            {
                foreach (var archivos in sftp.inputFile)
                {

                    if (archivos != null && archivos.ContentLength > 0 && archivos.ContentType.Equals("application/vnd.ms-excel"))
                    {
                        nombreArchivo = archivos.FileName;
                        byte[] data;
                        using (var csvLector = new StreamReader(archivos.InputStream))
                        {
                            using (MemoryStream ms = new MemoryStream())
                            {
                                csvLector.BaseStream.CopyTo(ms);
                                data = ms.ToArray();
                            }
                            csvLector.Close();


                            ViewBag.ArchivosCargados += string.Format("<b></b> <br />" + nombreArchivo);
                        }

                    }
                    else if (archivos == null)
                    {
                        ViewBag.Mensaje = "Favor de verificar No, ha seleccionado al menos un archivo con extension .csv";
                    }
                    else if (!archivos.ContentType.Equals("application/vnd.ms-excel"))
                    {
                        ViewBag.Mensaje = "Favor de verificar que el  archivo seleccionado sea con extension .csv";
                    }

                }
                return View();
            }
            catch (Exception e)
            {

                return View();
            }
        }//

        public ActionResult Consultar()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Consultar(string Selected, string SelectedBuscarUsuario, string SelectedBuscarCurso, string SelectedBuscarGrupo, string txtFiltro)
        {
            int algo = 0;
            int algo2 = 0;
            ArmarCadenas();
            if (!string.IsNullOrEmpty(Selected))
            {
                algo = Convert.ToInt32(Selected);

                if (algo == 1)
                {
                    if (!string.IsNullOrEmpty(SelectedBuscarUsuario))
                    {
                        algo2 = Convert.ToInt32(SelectedBuscarUsuario);
                        if (!string.IsNullOrEmpty(txtFiltro))
                        {   //get_user
                            pobjstrFiltro = txtFiltro;
                        }
                    }
                    RealizarBusqueda(algo, algo2);
                }
                else if (algo == 2)
                {
                    if (!string.IsNullOrEmpty(SelectedBuscarCurso))
                    {
                        algo2 = Convert.ToInt32(SelectedBuscarCurso);
                        if (!string.IsNullOrEmpty(txtFiltro))
                        {   //get_user
                            pobjstrFiltro = txtFiltro;
                        }
                    }
                    RealizarBusqueda(algo, algo2);
                }
                else if (algo == 3)
                {
                    if (!string.IsNullOrEmpty(SelectedBuscarCurso))
                    {
                        algo2 = Convert.ToInt32(SelectedBuscarCurso);
                    }
                    RealizarBusqueda(algo, algo2);
                }

            }
            if (!string.IsNullOrEmpty(txtFiltro))
            {
                ViewBag.Nombre = txtFiltro;
            }

            return View();
        }

        public ActionResult ObtenerCalificaciones()
        {
            ArmarCadenas();
            //RealizarBusqueda(1);
            return View("Calificaciones", pobjDtResultado);
        }

        public ActionResult RealizarBusquedaFiltrada(SftpModels sftp)
        {
            return View();
        }
        public int RealizarBusqueda(int id, int subId)
        {
            string n = string.Empty;
            int pobjCase = 0;
            StringBuilder pobjSbArmarCadenas = new StringBuilder();
            Urls = new List<string>();
            string pobjMetodo = string.Empty;

            switch (id)
            {
                case 1: n = "Buscar  Usuario";
                    pobjCase = 1;
                    switch (subId)
                    {
                        case 1: n = "NO HAY";
                            ViewBag.Mensaje = "Obtener los datos de perfil de un usuario";
                            pobjSbArmarCadenas = new StringBuilder();
                            pobjMetodo = string.Empty;
                            pobjSbArmarCadenas.Append(url);
                            pobjSbArmarCadenas.Append(pobjAdjuntarSlash);
                            pobjMetodo = endPoints.user.ToString();
                            pobjSbArmarCadenas.Append(pobjMetodo);
                            pobjSbArmarCadenas.Append(pobjExtension);
                            pobjSbArmarCadenas.Append(token);
                            pobjSbArmarCadenas.Append(pobjAdjuntar + pobjMetodoex);
                            pobjSbArmarCadenas.Append(Metodos.get_user);
                            ViewBag.Url = pobjSbArmarCadenas.ToString();
                            metodo = string.Empty;
                            metodo += pobjSbArmarCadenas.ToString() + pobjAdjuntar + "value=" + pobjstrFiltro;
                            ArmarMetodo(metodo);

                            break;
                        case 2: n = "NO HAY 2";
                            ViewBag.Mensaje = "Información acerca de todas las actividades";
                            pobjSbArmarCadenas = new StringBuilder();
                            pobjMetodo = string.Empty;
                            pobjSbArmarCadenas.Append(url);
                            pobjSbArmarCadenas.Append(pobjAdjuntarSlash);
                            pobjMetodo = endPoints.user.ToString();
                            pobjSbArmarCadenas.Append(pobjMetodo);
                            pobjSbArmarCadenas.Append(pobjExtension);
                            pobjSbArmarCadenas.Append(token);
                            pobjSbArmarCadenas.Append(pobjAdjuntar + pobjMetodoex);
                            pobjSbArmarCadenas.Append(Metodos.get_user_course_recent_activity);
                            pobjSbArmarCadenas.ToString();
                            ViewBag.Url = pobjSbArmarCadenas.ToString();
                            metodo = string.Empty;
                            metodo += pobjSbArmarCadenas.ToString() + pobjAdjuntar + "username=" + pobjstrFiltro;
                            ArmarMetodo(metodo);
                            break;
                        case 3: n = "NO HAY 3";
                            ViewBag.Mensaje = "Actividades que  debe entregar en un curso";


                            pobjSbArmarCadenas = new StringBuilder();
                            pobjMetodo = string.Empty;
                            pobjSbArmarCadenas.Append(url);
                            pobjSbArmarCadenas.Append(pobjAdjuntarSlash);
                            pobjMetodo = endPoints.user.ToString();
                            pobjSbArmarCadenas.Append(pobjMetodo);
                            pobjSbArmarCadenas.Append(pobjExtension);
                            pobjSbArmarCadenas.Append(token);
                            pobjSbArmarCadenas.Append(pobjAdjuntar + pobjMetodoex);
                            pobjSbArmarCadenas.Append(Metodos.get_user_course_activities_due);
                            pobjSbArmarCadenas.ToString();
                            ViewBag.Url = pobjSbArmarCadenas.ToString();
                            metodo = string.Empty;
                            metodo += pobjSbArmarCadenas.ToString() + pobjAdjuntar + "username=" + pobjstrFiltro;
                            ArmarMetodo(metodo);
                            break;
                        case 4: n = "NO HAY 4";
                            ViewBag.Mensaje = "Eventos del Usuario dentro de un curso";


                            pobjSbArmarCadenas = new StringBuilder();

Prueba-master/Projects/Consumir Aplicacion/Consumir Aplicacion/Views/Sftp/Calificaciones.cshtml
@using System.Data
@model DataTable
@{
    ViewBag.Title = "Cursos Calificaciones";
}

<h2>CursosCalificaciones</h2>


@{
    ViewBag.Title = "Consulta de Calificaciones Conduit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 align="center">Consulta de Resultados Conduit</h2>
<form id="FrmBuscar" method="post">
    <table align="center" class="table table-striped">
        <tr align="center">
            @foreach (DataColumn col in Model.Columns)
            {

                <th scope="col" align="center">

                    @if (col.Caption.Equals("grades_Id"))
                    {
                        ViewBag.Message = "hola";
                    }
                    else
                    {
                        @col.Caption;
                    }
                </th>
            }
        </tr>
        <tbody>
            @foreach (DataRow row in Model.Rows)
            {
                <tr align="center">
                    @foreach (var cell in row.ItemArray)
                    {
                        if (cell != null)
                        {

                            <td scope="col">@cell.ToString()</td>
                        }

                    }
                </tr>
            }
        </tbody>
    </table>

    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="row">


            </div>
        </div>

    </div>
</form>

Prueba-master/Projects/Consumir Aplicacion/Consumir Aplicacion/Views/Sftp/Consultar.cshtml
@model Consumir_Aplicacion.Models.SftpModels

@{
    ViewBag.Title = "Consulta de Resultados Conduit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 align="center">Consulta de Resultados Conduit</h2>

<form id="FrmBuscar" action="@Url.Action("Consultar", "Sftp")" method="post">
    <div class="row">
        <div class="card">
            <br /><br />
            <div class="col-sm-1">
                <br />
                @Html.DropDownList("Selected", new List<SelectListItem>
                    {
                    new SelectListItem{ Text="USUARIO", Value = "1" },
                    new SelectListItem{ Text="CURSOS", Value = "2" },
                    new SelectListItem{ Text="GRUPOS", Value = "3" },
                 }, new { @class = "btn btn-primary" })
                <br />
                <br />
            </div>
            <br />
            <br /><br />
            <div class="col-md-3" align="right" id="BuscarUsuario" style="display:none">

                @Html.DropDownList("SelectedBuscarUsuario", new List<SelectListItem>
                    {
                    new SelectListItem{ Text="Obtener los datos de perfil de un usuario", Value = "1" },
                    new SelectListItem{ Text="Información acerca de todas las actividades", Value = "2" },
                    new SelectListItem{ Text="Actividades que  debe entregar en un curso", Value = "3" },
                    new SelectListItem{ Text="Eventos del Usuario dentro de un curso", Value = "4" },
                    new SelectListItem{ Text="Calificaciones del Usuario ", Value = "5" },

                 }, new { @class = "btn btn-primary" })


            </div>

            <div class="col-md-3 col-md-offset-3" align="right" id="BuscarCurso" style="display:none">

                @Html.DropDownList("SelectedBuscarCurso", new List<SelectListItem>
                    {
                    new SelectListItem{ Text="Obtener los detalles del curso", Value = "1" },
                    new SelectListItem{ Text="Obtener todas las calificaciones del curso", Value = "2" },

                 }, new { @class = "btn btn-primary" })

            </div><div class="col-sm-1"></div>
            <div class="card-body">

                <p class=" text-right" align="center">
                    Ingrese los terminos de busqueda
                </p>
                <input type="text" class="form-control" align="right" id="txtFiltro" style="text-align:center;" name="txtFiltro" value="" placeholder="" />
                <br />
                <input type="submit" class="btn btn-primary btn-sm" style="padding:2px 2px" id="Consultar" name="btnResult" value="Consultar" />
                <br />
            </div>
        </div>
        <div class="col-sm-4" id="txta" style="display:none">



        </div>


        <div class="col-sm-4">
            <div class="row">
                <div class="col">


                </div>
                <div class="col">
                    @if (!string.IsNullOrEmpty(ViewBag.Nombre))
                    {
                        <span align="center" style="color:blue"> @Html.Raw("Tu nombre es    " + ViewBag.Nombre)</span>

                    }

                </div>

            </div>
        </div>
        


    </div>
</form>

<script src="~/Scripts/jquery-1.7.1.js"></script>
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.8.20.js"></script>
<script src="~/Scripts/jquery-ui-1.8.20.min.js"></script>
<link rel="stylesheet" type="text/css" href="~/Scripts/jquery-ui.css" />
<script>

    $("#Selected").change(function () {
        var Select = $("#Selected").val();
        var pobjIN = parseInt(Select);
        switch (pobjIN) {
            case 1:
                n = "Buscar  Usuario";

                console.log("Opcion elegida     " + pobjIN);
                $("#BuscarUsuario").show();
                $("#BuscarCurso").hide();
                $("#BuscarGrupo").hide();
                $('#txtFiltro').attr('placeholder', 'ej. Kifire');

                break;
            case 2:
                n = "Buscar Cursos";

                console.log("Opcion elegida     " + pobjIN);
                $("#BuscarCurso").show();
                $("#BuscarUsuario").hide();
                $("#BuscarGrupo").hide();
                $('#txtFiltro').attr('placeholder', 'ej. Asignatura_1');
                break;

            case 3:
                n = "Buscar Grupos";

                console.log("Opcion elegida     " + pobjIN);
                $("#BuscarGrupo").show();
                $("#BuscarUsuario").hide();
                $("#BuscarCurso").hide();
                $('#txtFiltro').attr('placeholder', 'ej. Grupo_1');
                break;

            default: n = "Nohay";
                break;
        }

    });



    $("#SelectedBuscarUsuario").change(function () {
        var Select = $("#SelectedBuscarUsuario").val();
        var pobjIN = parseInt(Select);

        switch (pobjIN) {
            case 1:
                n = "Buscar  Usuario";
                console.log("Opcion elegida     " + n);
                console.log("Obtener los datos de perfil de un usuario    " + pobjIN);


                break;
            case 2:
                n = "Información acerca de todas las actividades";
                console.log("Opcion elegida     " + n);
                console.log("Opcion elegida    " + pobjIN);

                break;

            case 3:
                n = "Actividades que  debe entregar en un curso";
                console.log("Opcion elegida     " + n);
                console.log("Opcion elegida     " + pobjIN);
                break;
            case 4:
                n = "Eventos del Usuario dentro de un curso";
                console.log("Opcion elegida     " + n);
                console.log("Opcion elegida    " + pobjIN);
                $("#txtFiltro").hide();
                $("#Consultar").hide();

                break;
            case 5:
                n = "Calificaciones del Usuario";
                console.log("Opcion elegida     " + n);
                console.log("Opcion elegida     " + pobjIN);
                $("#txtFiltro").hide();
                $("#Consultar").hide();

                break;

            default: n = "Nohay";
                break;
        }

    });


    $("#SelectedBuscarCurso").change(function () {
        var Select = $("#SelectedBuscarCurso").val();
        var pobjIN = parseInt(Select);


        switch (pobjIN) {
            case 1:
                n = "Obtener los detalles del curso";
                console.log("Opcion elegida     " + n);
                console.log("Obtener los datos de perfil de un usuario    " + pobjIN);


                break;
            case 2:
                n = "Obtener todas las calificaciones del curso";
                console.log("Opcion elegida     " + n);
                console.log("Opcion elegida    " + pobjIN);

                break;



            default: n = "Nohay";
                break;
        }

    });
</script>

Prueba-master/Projects/Consumir Aplicacion/Consumir Aplicacion/Views/Sftp/Index.cshtml
@model List<Consumir_Aplicacion.Models.SftpModels>
@{
    ViewBag.Title = "Subir Archivos por FTP para Conduit";

}

<h2 align="center">Subir Archivos por FTP para Conduit</h2>
<h2>
    @{


    }
</h2>





@*@using (Html.BeginForm("Action", "Controller", FormMethod.Post,
    new { enctype = "multipart/form-data" }))*@
<form id="form" method="post" enctype="multipart/form-data">
    @*@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {*@
    <div class="row">
        <div class="col-sm-4">
            <div class="card">
                <div class="container">
                    <p>Seleccione los  Archivos </p>
                    <input type="file" class="form-control-file" id="txtFile" name="inputFile" multiple />
                    <br />
                    <input type="submit" class="btn btn-primary btn-sm" style="padding:2px 2px" id="Upload" name="btnResult" value="Subir" onclick="prueba()" />
                    <br /><br />
                </div>
                <br />
            </div>

        </div>
        <div class="col-sm-4">
            <div class="col">
                @if (!string.IsNullOrEmpty(ViewBag.Mensaje))
                {
                    <span align="center" style="color:red">@ViewBag.Mensaje</span>

                }

            </div>

        </div>


        <div id="dialogo2" title="Mensaje:" style="display:none" align="center">
            <p style="color:red">Favor de Subir archivos con extension .csv</p>

        </div>

        

    </div>
    @*}*@
</form>

<script src="~/Scripts/jquery-1.7.1.js"></script>
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.8.20.js"></script>
<script src="~/Scripts/jquery-ui-1.8.20.min.js"></script>
<link rel="stylesheet" type="text/css" href="~/Scripts/jquery-ui.css" />
<script type="text/javascript">

    function prueba() {

        var extensionArchivo = $("#txtFile").val();
        var valorStr = extensionArchivo.substring(12);
        var dataString = $("#form").serialize();
        var nuevoValor = extensionArchivo.substring(extensionArchivo.lastIndexOf("."));
        console.log("@@@@  prueba   " + dataString);
        console.log("@@@@  extensionArchivo   " + valorStr);

        console.log("@@@@  extensionArchivo   " + extensionArchivo);
        if (nuevoValor != ".csv") {
            console.log("@@@@  extensionArchivo   " + extensionArchivo);

            $("#dialogo").show();
        }
        if (extensionArchivo == "") {
            console.log("@@@@  extensionArchivo   " + extensionArchivo);
            $("#dialogo").show();
        }


    }

</script>

Prueba-master/Projects/Consumir Aplicacion/Consumir Aplicacion/Views/Sftp/View1.cshtml
@model Consumir_Aplicacion.Models.SftpModels

@{
    ViewBag.Title = "View1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View1</h2>